### ISSUE TITLE
Research Samvera solutions

### ISSUE THREAD

**Issue by hortongn** [uclibs/uc_drc#1]
Gather examples and details on Samvera repository solutions.

* Look at official gems in https://github.com/samvera and https://github.com/samvera-labs

* Check the Samvera wiki (e.g. https://wiki.lyrasis.org/display/samvera/Samvera+Implementations%3A+In-production)

* Search and ask on Samvera Slack

* Identify institutions that have moved from DSpace to Samvera

**Comment by scherztc** [comment]
Required Field Matrix : https://wiki.lyrasis.org/display/samvera/Required+Feature+Matrix
DSpace Migration Institutes:: https://wiki.lyrasis.org/display/samvera/Data+Migration+from+DSpace+to+Hydra
DSpace Migration Presentation: https://drive.google.com/file/d/1cMvdMZg_vKFixP4L3KptRjl37XUtHEOA/view

**Comment by scherztc** [comment]
**See spreadsheet :** https://mailuc-my.sharepoint.com/:x:/g/personal/vanmiljf_ucmail_uc_edu/EdUd1ax6bgBBlQO199XExG0B260ikj1zMct4eHfog6FZOQ?e=cPg9vc

**Official Gems:**
Hyrax
Hyku
Valkyrie
Hydra-File-Characterization
Hydra-Derivatives
Hydra-Works
Avalon
Hydra-Role-Management
BrowseEverything

**Lab Gems:**
Houndstooth
Scooby Snacks
Dog Biscuits
newspaper_works
Hyrax-iiif_av 
samvera-shibboleth
Bulrax
digital_collections_elixir_example

**Community Gems:**
Blacklight
nulib/donut
Hull_Culture
B2H Toolkit
blacklight_oai_provider

**Samvera Institutions that have migrated:**
California State University
University of Michigan
Oregon Statue University
Duke University
University of Maryland
