### ISSUE TITLE
Create sandbox deployment strategy

### ISSUE THREAD

**Issue by hortongn** [uclibs/uc_drc#101]
The default branch should be deployed to curly.libraries.uc.edu.  Ideally the instance should auto-update nightly (git pull), but if a manual process is needed that is acceptable as well.  In either case, the process should be documented.

**Comment by crowesn** [comment]
3am daily pull and restart scheduled in cron. 

See crontab and `/opt/rails-apps/deric/` for configuration.

**Comment by crowesn** [comment]
Reopening due to bug in env variable assignment on curly.

When running the app in docker, the app should know whether host is curly or local. Find a way to pass host environment to container so it knows whether to set cantaloupe url to localhost or curly.

**Comment by crowesn** [comment]
Also need to point cron job on curly to bash script in scripts dir.
