### ISSUE TITLE
Docker up replaces my .env.development.local file

### ISSUE THREAD

**Issue by scherztc** [uclibs/uc_drc#117]
**Describe the bug**
When I have a custom .env.development.local file and then run docker-compose up -d.  It will replace the local with the .env.development.docker.  

This causes problems when developing locally.

**Comment by crowesn** [comment]
does your custom .env.development.local deviate from the .env.development file in the repo?

**Comment by hortongn** [comment]
Maybe the Docker script should just copy .env.development.docker to .env.development instead of .env.development.local?  It should still work on won't be overwriting the user's .local file.

**Comment by crowesn** [comment]
the .local will take precedence over .env.development

https://github.com/bkeepers/dotenv#what-other-env-files-can-i-use

**Comment by hortongn** [comment]
Right, but then it's the developer's problem if their .local file is screwing up something.  If a dev wants to override the application_url or database settings for some reason, they should be allowed to maintain their own .local file for that.
