### ISSUE TITLE
Configure circleCI

### ISSUE THREAD

**Issue by crowesn** [uclibs/uc_drc#12]
### Resources:
* CircleCI config in Scholar: https://github.com/uclibs/ucrate/pull/881

### Also get coveralls integration working:

Additions needed to .circleci/config.yml
* https://github.com/uclibs/ucrate/blob/develop/.circleci/config.yml#L46
* https://github.com/uclibs/ucrate/blob/develop/.circleci/config.yml#L84-L86

Create .coveralls.yml
* https://github.com/uclibs/ucrate/blob/develop/.coveralls.yml#L1

Get the repo token from https://coveralls.io/github/uclibs/uc_drc and add it to the circleci environment variable settings

Set up github to require passing coveralls checks for PR merges

**Comment by hortongn** [comment]
Assigned this to @scherztc since he should be able to get this set up using what he's learned on CircleCI with Scholar.

**Comment by crowesn** [comment]
Relies on #22
