### ISSUE TITLE
Change default branch from master to main

### ISSUE THREAD

**Issue by crowesn** [uclibs/uc_drc#66]
https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Comment by scherztc** [comment]
- [X] Move master to  main.
- [X] Push main.
- [X] change my default branch in my GitHub settings
- [X] Make new main branch rule.

If you need to rebase locally:

UPDATING LOCAL CLONES
If someone has a local clone, then can update their locals like this:

$ git checkout master
$ git branch -m master main
$ git fetch
$ git branch --unset-upstream
$ git branch -u origin/main
$ git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main

**Comment by scherztc** [comment]
Locally you might need to update:

$ git checkout main
$ git fetch
$ git branch --unset-upstream
$ git branch -u origin/main
$ git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
