### ISSUE TITLE
Analyze requirements for DRC metadata profiles

### ISSUE THREAD

**Issue by hortongn** [uclibs/uc_drc#7]
Determine the work and time needed to implement metadata profiles and collection-based user input forms.

Assumptions
* Use only one Hyrax work type
* Add all possible fields to that work type
* When new fields are added to the work type, the ADU will deploy changes.
* On a per-collection need, allow admins to hide the fields that are not needed.

**Comment by scherztc** [comment]
![Class Diagram for DRC](https://user-images.githubusercontent.com/5084562/79890681-d9924e80-83cd-11ea-8c09-ea34087360ef.png)

**Comment by scherztc** [comment]
Metadata Meeting
		Examine Field Mapping from DRC to DAC
		Strategy for :
			GUI for adding fields to forms.
			Handles
			Breadcrumbs
		Singluar Worktype
		Number of Admin Septs? 1000's
		Number of Workflows? 2

**Comment by scherztc** [comment]
Here is Hannah's Metadata Mapping for the DRC : https://mailuc-my.sharepoint.com/:x:/r/personal/vanmiljf_ucmail_uc_edu/Documents/digital-collections/dspace-migration-planning/drc_MAP_Updated2019.xlsx?d=w9ce850f62a684a74b901e1d18d551a99&csf=1&web=1&e=ZOahTH
