### ISSUE TITLE
Implement IIIF server

### ISSUE THREAD

**Issue by hortongn** [uclibs/uc_drc#72]
We will want to use a stand-alone IIIF server such as Cantaloupe, Loris, or IIPImage in our production environment.  We probably still want to use RIIF in development mode with ability to switch to something else for production.

Research the options and standup a test instance for testing.

**Comment by crowesn** [comment]
https://groups.google.com/g/samvera-tech/c/BGezJQhuIJQ/m/47Tmuy2QBAAJ

**Comment by crowesn** [comment]
https://gist.github.com/bess/30bba237d3d0df8fa2ebcbd6876053d0#file-delegates-rb-L173
