### ISSUE TITLE
Standup application in sandbox

### ISSUE THREAD

**Issue by hortongn** [uclibs/uc_drc#74]
Depends on: https://github.com/uclibs/uc_drc/issues/73

Let's get the application as it is right now running on curly.libraries.uc.edu.  It will be good to have a place to try the application or push up a branch for people to test when needed.

We will want Fedora and Solr content to persist between restarts

To make deploys easier, we should use capistrano (https://github.com/uclibs/uc_drc/issues/73)

**Comment by crowesn** [comment]
https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option
