### ISSUE TITLE
Test allinson_flex gem

### ISSUE THREAD

**Issue by hortongn** [uclibs/uc_drc#80]
Get the IU/Notch8 application up and running in a sandbox so that the allinson_flex gem and other features can be tested.

The PR/branch is located at  https://github.com/notch8/essi/pull/48

~~Add the https://github.com/samvera-labs/allinson_flex gem to uc_drc and make the branch available for James to test.~~

This appears to require special work types.  Instructions for generating them are in the README.  We will need just one work type called "Item" for now.

Any problems with the gem should be opened as issues on the allinson_flex repo.  We can also submit PR fixes.

**Comment by scherztc** [comment]
Requires Node.js ">=10.17.0"

**Comment by scherztc** [comment]
We will need to create our metadata profile for the WorkType = Item.
Use this as an example : config/metadata_profile/hyrax.yaml

**Comment by scherztc** [comment]
James and met and worked the Allinson Flex Gem to see what is available to do without access to the council, what things we still have questions about, and then what will it mean for our current work type.

1.  We are confident that we can create new work types, add and remove metadata, modifying labelling, add contextual help, and set our indexing type from the dashboard.

2.  We are still worried about how BulkRAX will interact with the fields and work types.  We are curious if the Allinson Flex gem will work with adding fields to Collections.  In the example YAMLs we see Collection as a possible Class.  Do Admin Sets have anything do with Allinson Flex?

3.  Next steps, we also tested what the generator does to our current work type.  We are going to attempt to run the generator on our work type first and then if need be remove our work type and then run the generator.  We also still need our own uc_drc metadata profile yaml.

**Comment by scherztc** [comment]
https://github.com/samvera-labs/allinson_flex
https://sc2020.sched.com/event/fCi7/poster-qa-notch8-allinson-flex
https://sc2020.sched.com/event/eIr8/flexible-metadata-in-hyrax-and-friends-with-allinson-flex
http://bit.ly/samvera2020
https://gitlab.com/notch8/flex_demo

**Comment by scherztc** [comment]
Closed with this PR : https://github.com/uclibs/uc_drc/pull/93
