### ISSUE TITLE
Docker: use solr config from app

### ISSUE THREAD

**Issue by crowesn** [uclibs/uc_drc#96]
When starting docker, copy and use the solr config from the app root. We don't want to maintain 2 copies of the solr config.

**Comment by crowesn** [comment]
@hortongn In scholar, does solr run on the application server? In our docker setup for deric, we have solr running in it's own container.

**Comment by hortongn** [comment]
@crowesn In production, Solr runs on its own server for Scholar.  2 web servers, a solr server, a fedora server, and a database server.
